spring.application.name=pridesys
server.port=8090

#spring.datasource.url=jdbc:oracle:thin:@//192.168.111.21:1521/PRIDEDEV19C
#spring.datasource.username=bms
#spring.datasource.password=bms
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true